#ifndef IO_CLASS_STORAGE_HEADER
#define IO_CLASS_STORAGE_HEADER

#define STOR_CMD_SIZE     0x10
#define STOR_CMD_SEEK     0x11
#define STOR_CMD_TELL     0x12
#define STOR_CMD_READ     0x13
#define STOR_CMD_WRITE    0x14

#endif //IO_CLASS_STORAGE_HEADER
