#!/usr/bin/perl
use File::Slurp;

sub is_opcode {
  my $line = shift();
  return (($line =~ m/^#define/) && !($line =~ m/OPCODE/));
}

my %opcode_map;
my $arg = shift;
for(read_file($arg)) {
  if(is_opcode($_)) {
    $_ =~ s/^\s+|\s+$//g;
    my @arr = split(/\s+/, $_);
    $opcode_map{$arr[2]} = $arr[1];
  }
}

print <<QQQ;
// AUTOGENERATED BY generate_debug_names.pl, DO NOT MODIFY

#ifndef DEBUG_NAMES_HEADER
#define DEBUG_NAMES_HEADER

char *inst_names[0x100];
char names_initialized = 0;

void init_names() {
  if(names_initialized) return;
  names_initialized = 1;

  for(int i=0; i<0xFF; i++)
    inst_names[i] = "unknown";

QQQ

print "  inst_names[$_] = \"$opcode_map{$_}\";\n" for(keys %opcode_map);

print <<QQQ;
}

#endif //DEBUG_NAMES_HEADER
QQQ
